"""
Build script for Simple_Scope with automatic versioning.

This script:
1. Retrieves version from git tags
2. Generates _version.py for the app
3. Generates Windows version info file for exe properties
4. Runs PyInstaller with the appropriate spec file

Usage:
    python build.py                    # Build single-file exe (default)
    python build.py --type single      # Build single-file exe
    python build.py --type directory   # Build directory-based distribution
"""

import subprocess
import argparse
from pathlib import Path


def get_git_version() -> str:
    """Get version from git tag.

    Returns:
        Version string from git describe, or "0.0.0" if not available.
    """
    try:
        result = subprocess.run(
            ["git", "describe", "--tags", "--always"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode == 0:
            version = result.stdout.strip()
            # Remove 'v' prefix if present (e.g., v1.0.0 -> 1.0.0)
            if version.startswith('v'):
                version = version[1:]
            return version
    except (subprocess.SubprocessError, OSError):
        pass
    return "0.0.0"


def generate_version_file(version: str, base_path: Path) -> Path:
    """Generate _version.py for the app.

    Args:
        version: Version string to write
        base_path: Project root directory

    Returns:
        Path to the generated file
    """
    version_file = base_path / 'Simple_Scope' / 'app' / '_version.py'
    version_file.write_text(f'version = "{version}"\n')
    print(f"Generated: {version_file}")
    return version_file


def parse_version_tuple(version: str) -> tuple[int, int, int, int]:
    """Parse version string into a 4-tuple of integers.

    Args:
        version: Version string (e.g., "1.2.3" or "1.2.3-4-gabc123")

    Returns:
        Tuple of (major, minor, patch, build) integers
    """
    # Handle versions like "1.2.3-4-gabc123" by taking only the base version
    base_version = version.split('-')[0]
    parts = base_version.split('.')

    # Convert to integers, defaulting to 0 for missing parts
    int_parts = []
    for i in range(4):
        if i < len(parts):
            try:
                int_parts.append(int(parts[i]))
            except ValueError:
                int_parts.append(0)
        else:
            int_parts.append(0)

    return tuple(int_parts)


def generate_windows_version_info(version: str, base_path: Path) -> Path:
    """Generate Windows version info file for exe properties.

    Args:
        version: Version string
        base_path: Project root directory

    Returns:
        Path to the generated version info file
    """
    parts = parse_version_tuple(version)

    version_info = f'''# UTF-8
#
# Windows version info file for PyInstaller
# Auto-generated by build.py
#
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={parts},
    prodvers={parts},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          '040904B0',
          [
            StringStruct('CompanyName', 'Niel Walker'),
            StringStruct('FileDescription', 'Oscilloscope Screenshot Capture Application'),
            StringStruct('FileVersion', '{version}'),
            StringStruct('InternalName', 'Simple_Scope'),
            StringStruct('LegalCopyright', 'MIT License'),
            StringStruct('OriginalFilename', 'Simple_Scope.exe'),
            StringStruct('ProductName', 'Simple Scope'),
            StringStruct('ProductVersion', '{version}'),
          ]
        )
      ]
    ),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
'''
    info_file = base_path / 'pyinstaller_config' / 'version_info.txt'
    info_file.write_text(version_info)
    print(f"Generated: {info_file}")
    return info_file


def build(build_type: str = 'single') -> None:
    """Run PyInstaller build with version generation.

    Args:
        build_type: Either 'single' for single-file exe or 'directory' for folder distribution
    """
    base_path = Path(__file__).parent
    spec_file = 'single_file.spec' if build_type == 'single' else 'directory.spec'
    spec_path = base_path / 'pyinstaller_config' / spec_file

    # Get version from git
    version = get_git_version()
    print(f"Building Simple Scope version: {version}")
    print(f"Build type: {build_type}")
    print("-" * 40)

    # Generate version files
    generate_version_file(version, base_path)
    generate_windows_version_info(version, base_path)

    print("-" * 40)
    print("Running PyInstaller...")

    # Run PyInstaller
    result = subprocess.run(
        ["pyinstaller", str(spec_path), "--noconfirm"],
        cwd=base_path,
    )

    if result.returncode == 0:
        print("-" * 40)
        print(f"Build complete! Output in: {base_path / 'dist' / 'onefile'}")
    else:
        print(f"Build failed with return code: {result.returncode}")


def main():
    parser = argparse.ArgumentParser(
        description='Build Simple_Scope with automatic versioning from git tags'
    )
    parser.add_argument(
        '--type',
        choices=['single', 'directory'],
        default='single',
        help='Build type: single (one-file exe) or directory (folder distribution)'
    )
    args = parser.parse_args()
    build(args.type)


if __name__ == "__main__":
    main()
