"""
Build helper script for Simple_Scope.

Reads the version from git tags and writes a PyInstaller-compatible
Windows version info file (version_info.txt) that the spec files reference
for EXE properties (File Version, Product Version, etc.).

Usage:
    python build.py
"""

import subprocess
import sys
import re
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve()
PROJECT_ROOT = SCRIPT_DIR.parent
VERSION_INFO_FILE = SCRIPT_DIR / "version_info.txt"
VERSION_PY_FILE = PROJECT_ROOT / "Simple_Scope" / "app" / "_version.py"


def get_version_from_git() -> str:
    """Get version string from git describe --tags --always."""
    try:
        result = subprocess.run(
            ["git", "describe", "--tags", "--always"],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode == 0:
            version = result.stdout.strip()
            if version.startswith("v"):
                version = version[1:]
            return version
        print(f"git describe failed: {result.stderr.strip()}", file=sys.stderr)
    except (subprocess.SubprocessError, OSError, FileNotFoundError) as e:
        print(f"git describe exception: {e}", file=sys.stderr)
    return "0.0.0"


def parse_version(version_str: str) -> tuple:
    """
    Parse a version string into a 4-tuple of ints for Windows version info.

    Handles:
        "1.2.3"            -> (1, 2, 3, 0)
        "1.2.3-5-gabcdef"  -> (1, 2, 3, 5)   (N commits past the tag)
        "abc1234"          -> (0, 0, 0, 0)    (bare commit hash, no tags yet)
    """
    match = re.match(r"^(\d+)\.(\d+)\.(\d+)(?:-(\d+)-g[0-9a-f]+)?", version_str)
    if match:
        major = int(match.group(1))
        minor = int(match.group(2))
        patch = int(match.group(3))
        build = int(match.group(4)) if match.group(4) else 0
        return major, minor, patch, build
    return 0, 0, 0, 0


def write_version_info(version_str: str, version_tuple: tuple) -> None:
    """Write a PyInstaller-compatible Windows VERSIONINFO file."""
    major, minor, patch, build = version_tuple
    file_ver_str = f"{major}.{minor}.{patch}.{build}"

    content = f"""\
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, {build}),
    prodvers=({major}, {minor}, {patch}, {build}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          '040904B0',
          [StringStruct('CompanyName', ''),
           StringStruct('FileDescription', 'Simple Scope'),
           StringStruct('FileVersion', '{file_ver_str}'),
           StringStruct('InternalName', 'Simple_Scope'),
           StringStruct('LegalCopyright', ''),
           StringStruct('OriginalFilename', 'Simple_Scope.exe'),
           StringStruct('ProductName', 'Simple Scope'),
           StringStruct('ProductVersion', '{version_str}')])
      ]
    ),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
    VERSION_INFO_FILE.write_text(content, encoding="utf-8")
    print(f"Wrote version info to: {VERSION_INFO_FILE}")


def write_version_py(version_str: str) -> None:
    """Write app/_version.py so the packaged EXE can resolve its version at runtime."""
    content = f'# Generated by build.py — do not edit manually\nversion = "{version_str}"\n'
    VERSION_PY_FILE.write_text(content, encoding="utf-8")
    print(f"Wrote version module to: {VERSION_PY_FILE}")


def main():
    version_str = get_version_from_git()
    version_tuple = parse_version(version_str)
    print(f"Version: {version_str}  ->  file version tuple {version_tuple}")
    write_version_info(version_str, version_tuple)
    write_version_py(version_str)


if __name__ == "__main__":
    main()
