"""
Post-build cleanup script for Simple_Scope.

Removes temporary files and directories created during the build process:
  - build/           PyInstaller intermediate build artifacts
  - version_info.txt Windows version info file generated by pre_build.py

Usage:
    python post_build.py
"""

import shutil
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve()
PROJECT_ROOT = SCRIPT_DIR.parent


def remove_dir(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
        print(f"Removed directory: {path}")
    else:
        print(f"Skipped (not found): {path}")


def remove_file(path: Path) -> None:
    if path.exists():
        path.unlink()
        print(f"Removed file: {path}")
    else:
        print(f"Skipped (not found): {path}")


def main():
    remove_dir(PROJECT_ROOT / "build")
    remove_file(SCRIPT_DIR / "version_info.txt")
    print("Post-build cleanup complete.")


if __name__ == "__main__":
    main()
