# -*- mode: python ; coding: utf-8 -*-

import sys
from pathlib import Path
import os

block_cipher = None

# Get the base path of the project
base_path = Path(os.path.abspath(SPECPATH)).parent

# Version info file for Windows exe properties (generated by build.py)
version_info_file = base_path / 'pyinstaller_config' / 'version_info.txt'
version_info = str(version_info_file) if version_info_file.exists() else None

# Data files to include
data_files = [
    (str(base_path / 'Simple_Scope' / 'app'), 'app'),
    (str(base_path / 'Simple_Scope' / 'tests'), 'tests'),
]

# Add any additional files or directories that need to be included
added_files = []

a = Analysis(
    [str(base_path / 'Simple_Scope' / 'main.py')],
    pathex=[str(base_path)],
    binaries=[],
    datas=data_files + added_files,
    hiddenimports=['pyvisa', 'pyvisa_py'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Simple_Scope',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(base_path / r'Simple_Scope/resources/icons/simple_scope_icon.ico'),
    version=version_info,  # Windows version info (generated by build.py)
    distpath=str(base_path / 'dist' / 'onefile'),  # Custom output directory
)