"""
Version retrieval for Simple Scope application.

Retrieves version from:
1. _version.py (generated by setuptools-scm when installed as package)
2. Git tags at runtime (for development/source runs)
3. Fallback to "unknown"
"""

from pathlib import Path


def _get_version_from_scm_file() -> str | None:
    """Try to get version from setuptools-scm generated file."""
    try:
        from . import _version
        return _version.version
    except ImportError:
        return None


def _get_version_from_git() -> str | None:
    """Try to get version from git tags at runtime."""
    import subprocess # since this is more for development, lets not load it in the build
    try:
        # Find the git root directory
        module_dir = Path(__file__).parent
        git_dir = module_dir.parent.parent.parent  # Navigate up to git root

        result = subprocess.run(
            ["git", "describe", "--tags", "--always"],
            cwd=git_dir,
            capture_output=True,
            text=True,
            timeout=5,
        )

        if result.returncode == 0:
            version = result.stdout.strip()
            # Remove 'v' prefix if present (e.g., v1.0.0 -> 1.0.0)
            if version.startswith('v'):
                version = version[1:]
            return version
        return None
    except (subprocess.SubprocessError, OSError, FileNotFoundError):
        return None


def get_version() -> str:
    """Get the application version.

    Returns:
        Version string from git tag, setuptools-scm, or "unknown" as fallback.
    """
    # Try setuptools-scm generated file first (for installed packages)
    version = _get_version_from_scm_file()
    if version:
        return version

    # Try git describe (for development/source runs)
    version = _get_version_from_git()
    if version:
        return version

    # Fallback
    return "unknown"


__version__ = get_version()
